version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudprojectmarker"
s3_bucket = "markingtestdemodeploy"
s3_prefix = "cloudprojectmarker"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
# parameter_overrides = "RecaptchaSiteKey=XXXXXX RecaptchaSercetKey=YYYYY"

